# Generated by Django 5.1 on 2024-10-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_address_cartbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_no',
            field=models.IntegerField(default='+91'),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.IntegerField(),
        ),
    ]
