# Generated by Django 5.1 on 2024-09-23 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.store')),
            ],
            options={
                'verbose_name': 'food_category',
                'verbose_name_plural': 'food_category',
                'db_table': 'restaurant_food_category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg_or_meat_image', models.ImageField(upload_to='foods')),
                ('food_name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('image', models.ImageField(upload_to='foods')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.food_category')),
            ],
            options={
                'verbose_name': 'foods',
                'verbose_name_plural': 'foods',
                'db_table': 'restaurant_foods',
                'ordering': ['-id'],
            },
        ),
    ]
