# Generated by Django 5.1 on 2024-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_food_category_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='veg_or_meat_image',
        ),
        migrations.AddField(
            model_name='foods',
            name='is_veg',
            field=models.BooleanField(default=False),
        ),
    ]
