# Generated by Django 5.1 on 2024-09-23 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_foods_veg_or_meat_image_foods_is_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='food_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.food_category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foods',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.store'),
        ),
    ]
