# Generated by Django 5.1 on 2024-10-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_foods_food_category_alter_foods_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='rating',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='rating',
            new_name='amount',
        ),
    ]
